### PR TITLE
Tables Stream Extra Data

### LINKED ISSUE #221: ArgumentOutOfRangeException thrown during computation of TypeRefHash
We frequently see this exception in our processing. I don't know yet whether this is caused by a bug in PeNet or whether the .NET header is malformed.

Full stack trace:
```c#
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at PeNet.Header.Net.MetaDataTablesHdr.ParseTableDefinitions()
   at PeNet.Header.Net.MetaDataTablesHdr.get_TableDefinitions()
   at PeNet.Header.Net.MetaDataTablesHdr.ParseTable[T](MetadataToken token)
   at PeNet.Header.Net.MetaDataTablesHdr.ParseMetaDataTables()
   at PeNet.Header.Net.TypeRefHash.ComputeHash()
   at PeNet.PeFile.get_TypeRefHash()
```

This malware sample for example leads to the exception: https://www.virustotal.com/gui/file/f88e743fdd410a89b7084076883164120e3abe7f8f08ad65bb0fec05b392d3b1/

### PR DESCRIPTION
**Pull request by Washi1337**
Fixes #221.

One potential issue with this implementation however is the following: If the input PE file does not have extra data stored, and we _still_ write a value to `ExtraData` (essentially adding extra data), we will be overwriting data of the first column of the first table (usually the Module table). A similar issue can be found when there _is_ extra data stored in the PE file, but we try to remove it.

I don't think PeNet currently supports changing dynamically sized structures right now (as it is doing byte patching on the fly). Should we just completely forbid these situations with an exception?

Side note: I think this may be a core issue of PeNet itself, with regards to the lazy loading and the models being completely mutable. For example, the behavior of `ParseTableDefinitions` is dependent on the value of `HeapSizes`. This means that if we change `HeapSizes` _before_ `ParseTableDefinitions` is called (e.g. by accessing `Tables`), then this has consequences on how these tables are read. Accessing first the tables and _then_ changing the heap sizes _will_ read the tables properly.

### CODE REVIEW

**Comment by Washi1337** [comment]
Also, another question, should the XMLDoc of `HeapSizes` be updated, and `HeapSizes` class be changed to include the `HasExtraData` flag as well?

**Comment by secana** [comment]
Hi @Washi1337, first thanks a lot for the PR!

I guess throwing an exception is the best solution. It's better than silently breaking a PE file.

Updating the XMLDocs and classes sounds like a good idea. I'll merge the PR as soon as you give me the "go".

**Comment by Washi1337** [comment]
Should we move the `HasExtraData` property into the `HeapSizes` class only then? Or leave it inside the `MetadataTablesHdr` class instead?

**Comment by Washi1337** [comment]
If nothing needs to be changed from my commit as it is now, then this PR can be merged :)

**Review by secana — APPROVED** [review]

**Comment by secana** [comment]
@Washi1337 thanks alot for the PR. I'll merge and release a new version right now!

**Pull request merged**
