### PR TITLE
WIP: Add capability to extract icons from PeFile.

### PR DESCRIPTION
**Pull request by LarsSchlieper**

### CODE REVIEW

**Comment by rngcntr** [comment]
@secana You can already have a look at the implementation and review it, even though we marked the PR as WIP. We expect any upcoming changes to be stylistic, e.g. moving tests elsewhere

**Review by secana — APPROVED** [review]

**Comment by secana** [comment]
@rngcntr looks good so far :)

**Comment by LarsSchlieper** [comment]
Windows tests also passing.
Ready for final review.

**Review by secana — APPROVED** [review]

**Comment by secana** [comment]
I'll merge and release a new preview version. If it worked for some time in production, I'll release the final version.

**Pull request merged**
